---
version: 3

options:
  package_manager_path: /usr/bin/microdnf

dependencies:
  galaxy:
    collections:
      - name: ansible.controller
        version: "4.5.1"
      - name: ansible.windows
        version: "1.14.0"
      - name: community.windows
        version: "2.1.0"
      - name: community.vmware
        version: "4.2.0"
      - name: vmware.vmware_rest
        version: "3.0.0"

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8:latest

additional_build_files:
  - src: files
    dest: configs

additional_build_steps:
  prepend_galaxy:
    - COPY _build/configs/ansible.cfg /etc/ansible/ansible.cfg
