image: quay.io/zleblanc/bitbucket-builder:v1

pipelines:
  default:
    - step:
        name: 'Build execution environment'
        deployment: master
        script:
          - ansible-builder --help
