image: quay.io/centos/centos:stream9

pipelines:
  default:
    - step:
        name: 'Install ansible-builder'
        deployment: master
        script:
          - python3 -m pip install ansible-builder
