---
version: 3

options:
  package_manager_path: /usr/bin/microdnf

images:
  base_image:
    name: 'registry.redhat.io/ansible-automation-platform-24/de-minimal-rhel8:latest'
    
dependencies:
  python:
    - aiohttp
    - aiokafka
    - requests
  system:
    - pkgconf-pkg-config [platform:rpm]
    - systemd-devel [platform:rpm]
    - gcc [platform:rpm]
    - python39-devel [platform:rpm]
  galaxy:
    collections:
      - name: ansible.eda
      - name: cloin.eda
      - name: cloin.datadog
      - name: ansible.utils
      - name: dynatrace.event_driven_ansible
      - name: cloin.prometheus
