---
version: 3

options:
  package_manager_path: /usr/bin/microdnf

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel8:latest

dependencies:
  system:
    - curl
    - git
  python:
    - requests
    - passlib
    - lxml
    - xmltodict
    - jmespath
    - packaging
  galaxy:
    collections:
      - name: community.general
        version: "6.6.0"
      - name: awx.awx
        version: "22.7.0"
      - name: ansible.controller
        version: "4.5.0"
      - name: theforeman.foreman
        version: "3.14.0"
      - name: azure.azcollection
        version: "1.15.0"
      - name: ansible.windows
        version: "1.9.0"
      - name: ansible.utils
        version: "2.9.0"
      - name: community.windows
        version: "1.9.0"
      - name: community.general
        version: "6.6.0"
      - name: chocolatey.chocolatey
        version: "1.4.0"
      - name: servicenow.itsm
        version: "2.1.0"

additional_build_steps:
  prepend_final: |
    RUN curl -L https://aka.ms/InstallAzureCli | bash