---
collections:
  - name: ansible.windows
    version: 1.9.0
  - name: community.windows
    version: 1.9.0
  - name: community.general
    version: 6.6.0
  - name: chocolatey.chocolatey
    version: 1.4.0
  - name: servicenow.itsm
    version: 2.1.0