---
version: 3

options:
  package_manager_path: /usr/bin/microdnf

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel8:latest

additional_build_steps:
  append_final:
    - RUN ln -s /usr/share/ansible/collections /usr/share/automation-controller/collections