---
- name: Build an execution environment
  hosts: "{{ build_host | default(omit) }}"
  gather_facts: false
  become: false

  tasks:
    - name: Create temporary build directory
      register: r_tmp_dir
      ansible.builtin.tempfile:
        state: directory
        suffix: ee_checkout

    - name: test
      ansible.builtin.command: "ls {{ playbook_dir }}"

    - name: Copy destination to remote
      ansible.builtin.copy:
        src: "/runner/project/{{ ee_name }}/"
        dest: "{{ r_tmp_dir.path }}/"
        mode: "0644"

    - name: Cleanup temporary build directory
      when: r_tmp_dir.path is defined
      ansible.builtin.file:
        path: "{{ r_tmp_dir.path }}"
        state: absent
