---
- name: Build an execution environment
  hosts: "{{ build_host | default(omit) }}"
  gather_facts: false
  become: false

  tasks:
    - name: Create temporary build directory
      register: r_tmp_dir
      ansible.builtin.tempfile:
        state: directory
        suffix: ee_checkout

    - name: Checkout definitions
      ansible.builtin.git:
        repo: git@bitbucket.org:zach-leblanc/ansible-execution-environments.git
        dest: "{{ r_tmp_dir.path }}"
        version: "{{ commit_hash | ternary(commit_hash, omit) }}"
        accept_hostkey: true
        key_file: /home/zach/.ssh/id_rsa

    - name: Load EE definition from file
      register: r_ee_def_yml
      ansible.builtin.slurp:
        src: "{{ r_tmp_dir.path + '/' + ee_name + '/execution-environment.yml' }}"

    - name: Create var from ee definition
      ansible.builtin.set_fact:
        ee_definition: "{{ r_ee_def_yml.content | b64decode | from_yaml }}"

    - name: Build and publish the EE
      ansible.builtin.include_role:
        name: infra.ee_utilities.ee_builder
      vars: # noqa var-naming[no-role-prefix]
        ee_base_registry_username: "{{ ee_base_reg_user }}"
        ee_base_registry_password: "{{ ee_base_reg_password }}"
        ee_registry_dest: "{{ ee_dest_reg }}"
        ee_registry_username: "{{ ee_dest_reg_user }}"
        ee_registry_password: "{{ ee_dest_reg_password }}"
        ee_ah_host: "{{ lookup('env', 'AH_HOST') | default(omit) }}"
        ee_ah_token: "{{ lookup('env', 'AH_TOKEN') | default(omit) }}"
        ee_builder_dir_clean: true
        ee_list:
          - name: "{{ ee_name }}"
            tag: "{{ commit_hash | default(omit) }}"
            images: "{{ ee_definition.images | default({}) }}"
            dependencies: "{{ ee_definition.dependencies | default({}) }}"
            options: "{{ ee_definition.options | default({}) }}"
            build_steps: "{{ ee_definition.build_steps | default({}) }}"
            build_items: "{{ ee_definition.build_items | default([]) }}"
            build_files: "{{ ee_definition.build_files | default({}) }}"

    - name: Cleanup temporary build directory
      when: r_tmp_dir.path is defined
      ansible.builtin.file:
        path: "{{ r_tmp_dir.path }}"
        state: absent
