---
version: 2

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--ignore-certs'

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-22/ee-29-rhel8:latest

dependencies:
  galaxy: requirements.yml
  python: requirements.txt