---
collections:
  - name: amazon.aws
    version: 1.4.1
  - name: awx.awx
    version: 17.1.0
  - name: ansible.utils
    version: 2.0.2
  - name: ansible.windows
    version: 1.5.0
  - name: community.crypto
    version: 1.6.1
  - name: community.hashi_vault
    version: 1.1.3
  - name: community.aws
    version: 1.4.0
  - name: community.windows
    version: 1.3.0