name: publish-execution-environments
run-name: ${{ github.actor }} publishing execution environments
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      ee-matrix: ${{ steps.ee-changes.outputs.changed-ees }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
            fetch-depth: 2

      - name: Identify changed files
        uses: tj-actions/changed-files@v35
        id: file-changes
        with:
          since_last_remote_commit: true
          files: 'execution-environments/**/*'
          files_ignore: |
            **/README.md
            **/.files/*

      - name: Determine EEs to build
        id: ee-changes
        uses: ./.github/actions/changed-ee-contexts
        with: 
          changed-files: ${{ steps.file-changes.outputs.all_changed_files }}

  publish-ee-changes:
    needs: [ setup ]
    strategy:
      matrix:
        value: ${{ needs.setup.outputs.ee-matrix }}
    uses:  ./.github/workflows/deploy.yml
    with:
      EE_FOLDER_NAME: ${{ needs.setup.outputs.ee-matrix }}
      EE_IMAGE_TAG: 'latest'
      QUAY_USERNAME: 'zleblanc'
      REDHAT_USERNAME: zleblanc@redhat.com
    secrets:
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
      REDHAT_PASSWORD: ${{ secrets.REDHAT_PASSWORD }}
      AH_TOKEN: ${{ secrets.AH_TOKEN }}
